server:
  port: 8765


auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    id: ace-gate  #不填则默认读取spring.application.name
    secret: 123456

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
logging:
  level:
    com.github.wxiaoqi.security.gate.v2: info

spring:
  redis:
      database: 2
      host: 192.168.11.234
      jedis:
        pool:
            max-active: 20
      password: 123456
  cloud:
     gateway:
       discovery:
         locator:
           lowerCaseServiceId: true
           enabled: true
       routes:
        # =====================================
        - id: ace-auth
          uri: lb://ace-auth
          order: 8000
          predicates:
          - Path=/api/auth/**
          filters:
          - StripPrefix=2
        - id: ace-admin
          uri: lb://ace-admin
          order: 8001
          predicates:
          - Path=/api/admin/**
          filters:
          - StripPrefix=2
        - id: ace-pms
          uri: lb://ace-pms
          order: 8002
          predicates:
          - Path=/api/pms/**
          filters:
          - StripPrefix=2

gate:
  ignore:
    startWith: /auth/jwt


