
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.11.234:8848
    sentinel:
      transport:
        dashboard: 192.168.11.234:8088
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 0
    host: 192.168.11.234
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-idle: 100
      max-wait: 1000
      max-idle: 8
      min-idle: 0
      timeout: 3000
    host: ${RABBIT_MQ_HOST:192.168.11.234}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

   